### ISSUE TITLE
Notice 'forcing apt update' on every run

### ISSUE THREAD

**Issue by sts** [puppetlabs/puppetlabs-puppet_agent#161] opened 2016-09-24 05:01 UTC
The module keeps notifying about a forced apt update runs on every run, although apt update is never executed.

```
Notice: forcing apt update for pc_repo PC1
Notice: /Stage[main]/Puppet_agent::Osfamily::Debian/Notify[pc_repo_force]/message: defined 'message' as 'forcing apt update for pc_repo PC1'
Debug: /Stage[main]/Puppet_agent::Osfamily::Debian/Notify[pc_repo_force]: The container Class[Puppet_agent::Osfamily::Debian] will propagate my refresh event
Debug: Class[Puppet_agent::Osfamily::Debian]: The container Stage[main] will propagate my refresh event
Debug: Class[Puppet_agent::Osfamily::Debian]: The container Class[Puppet_agent::Prepare] will propagate my refresh event
Debug: Class[Puppet_agent::Prepare]: The container Stage[main] will propagate my refresh event
Debug: Class[Puppet_agent::Prepare]: The container Class[Puppet_agent] will propagate my refresh event
Debug: Class[Puppet_agent]: The container Stage[main] will propagate my refresh event
Debug: Evicting cache entry for environment 'production'
```

```
# puppet --version
4.6.2
```

**Comment by jordigg** [comment] 2017-03-09 17:16
Agree with this, this always flags machines are being on a "change" state.
I would avoid forcing apt updates. Providing a parameter to select if you want them or not would be beneficial. Otherwise leave it to the user's choice to run a system-wide apt-update when they need.

**Comment by MikaelSmith** [comment] 2017-03-09 22:08
This appears to be a duplicate of https://github.com/puppetlabs/puppetlabs-puppet_agent/issues/132.

**Closed by MikaelSmith** 2017-03-09 22:08 UTC
