### ISSUE TITLE
Upgrade from puppet 3.8.7 doesn't work when strict_variables enabled

### ISSUE THREAD

**Issue by TomaszUrugOlszewski** [puppetlabs/puppetlabs-puppet_agent#196] opened 2016-12-11 10:03 UTC
Hello,

puppet_agent doesn't work with puppetserver 2.7.2-1puppetlabs1 when strict_variables enabled.

Some quick changes that I made to make it work, not sure if are correct:

```
diff --git a/manifests/init.pp b/manifests/init.pp
index 55a981e..e13161f 100644
--- a/manifests/init.pp
+++ b/manifests/init.pp
@@ -71,7 +71,7 @@ class puppet_agent (
     }
 
     $aio_upgrade_required = ($is_pe == false and $_expected_package_version != undef) or
-      ($::aio_agent_version != undef and $_expected_package_version != undef and
+      (getvar('::aio_agent_version') != undef and $_expected_package_version != undef and
         versioncmp("${::aio_agent_version}", "${_expected_package_version}") < 0)
 
     if $::architecture == 'x86' and $arch == 'x64' {
diff --git a/manifests/prepare.pp b/manifests/prepare.pp
index 8b45932..abe2a50 100644
--- a/manifests/prepare.pp
+++ b/manifests/prepare.pp
@@ -67,13 +67,13 @@ class puppet_agent::prepare(
       }
 
       # The mco_*_config facts will return the location of mcollective config (or nil), prefering PE over FOSS.
-      if $::mco_server_config {
+      if getvar('::mco_server_config') {
         class { 'puppet_agent::prepare::mco_server_config':
           before => Class[$_osfamily_class],
         }
         contain puppet_agent::prepare::mco_server_config
       }
-      if $::mco_client_config {
+      if getvar('::mco_client_config') {
         class { 'puppet_agent::prepare::mco_client_config':
           before => Class[$_osfamily_class],
         }
```

**Comment by MikaelSmith** [comment] 2016-12-21 00:46
Is this a duplicate of https://github.com/puppetlabs/puppetlabs-puppet_agent/issues/141?

**Closed** 2016-12-22 07:45 UTC
