### ISSUE TITLE
install_puppet.bat.erb does not respect nodes running in non-"production" environments

### ISSUE THREAD

**Issue by james-powis** [puppetlabs/puppetlabs-puppet_agent#126] opened 2016-06-22 17:53 UTC
upgrading puppet causes puppet.conf file environment setting to revert to default explicitly. For nodes living in other environments this can cause issues. This does not impact situations where an enc is overriding environment. 

I will submit a PR with the appropriate fix.

**Comment by MikaelSmith** [comment] 2016-06-23 22:10
@Iristyle is this the expected behavior for the MSI?

**Comment by MikaelSmith** [comment] 2016-06-23 22:13
Thanks! Filed [MODULES-3517](https://tickets.puppetlabs.com/browse/MODULES-3517) to help us track it.

**Comment by james-powis** [comment] 2016-06-23 22:22
For completeness before upgrade puppet.conf had:
[agent]
...
environment = customers
server = puppet.master.mydomain.com

Post upgrade:
[agent]
environment =production
server =puppet.master.mydomain.com

Notice the changing of spacing, all other lines were left alone spacing wise and no settings were missing.

**Comment by brettswift** [comment] 2016-06-29 21:30
If you remove the environment completely, because you are relying on it getting it's environment from the console node group / environment classifier..   then this will assign `environment=master`. 

Is someone assigned to this? If not I might be able to look at this, as we have ~100 windoze to migrate fairly soon.

**Comment by MikaelSmith** [comment] 2016-06-29 22:07
The Node Classifier will be authoritative, unless you specifically set it up to defer to the agent. However, I agree that the default should probably not be to touch the environment setting.

**Comment by james-powis** [comment] 2016-06-29 22:54
I think that regardless of the behavior of the MSI in the future, ultimately for backwards compatibility the MSI execution this module is performing will have to pass PUPPET_AGENT_ENVIRONMENT="$::environment" in order to provide full matrix support.

**Comment by glennsarti** [comment] 2016-06-29 22:56
@james-powis I think I'm beginning to lean that way too.

**Comment by MikaelSmith** [comment] 2016-07-06 17:53
Merged https://github.com/puppetlabs/puppetlabs-puppet_agent/pull/127.

**Closed** 2016-07-06 17:53 UTC
